apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb-svc
spec:
  ports:
    - port: 27017
      name: mongo-port
  clusterIP: None
  selector:
    app: mongodb # This must match .spec.selector.matchLabels of the statefulset.

